### ISSUE TITLE
Source files or tips to make it work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [guillaumebriday/traefik-custom-error-pages#3]
Hi!

Is your traefik-custom-error-pages docker image private? I was wondering if its possible to see how its implemented. If I could grasp more and possibly if I get it to work so I might add custom error pages on my own sites.

**Comment by guillaumebriday** [comment]
Hey !

You're literally on the repository that is used to build the image and the pages. I use nothing more that you can see here to build the image and use it in production.

If you have any specific questions, do not hesitate !

Thanks

**Comment by thepenguinthatwants** [comment]
Oooh so the files were inside .cloud directory. Sorry my mistake earlier I thought they were  related to the https://docs.traefik.io/configuration/commons/#custom-error-pages

Your was based on LABEL traefik.frontend.rule="HostRegexp:{catchall:.*}"
catching all the sites that were not used already? 

How did you know which priority belongs to what and which one is right? traefik.frontend.priority="1" .

Thanks for the help this is very great and cool. Not sure if I can manage to get this work on my setup but I'll try more.

**Comment by guillaumebriday** [comment]
> Your was based on LABEL traefik.frontend.rule="HostRegexp:{catchall:.*}"
catching all the sites that were not used already?

Almost, `HostRegexp:{catchall:.*}` is used to respond to all requests, and the priority="1" works because this is the smallest integer available in traefik. So this container has the lowest priority possibe even if others containers has no priority set.

I updated the readme because it was not clear, could you tell me if it make sense ?

Thank you

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for explaining. 

Now it looks much better. 

Thank you!!
